package com.senosy.newsapp.utils

const val STATUS_CODE_UNAUTHORIZED_ERROR = 401
const val STATUS_CODE_SERVER_ERROR = 500
const val STATUS_CODE_NETWORK_ERROR = 402
const val STATUS_CODE_TIMEOUT_ERROR = 504
const val PERIOD_VALUE = "7"
const val PREF_FIRST_TIME="FIRST_TIME"
const val FAVOURITE_COUNTRY = "FAVOURITE_COUNTRY"
const val FAVOURITE_TAGS = "FAVOURITE_TAGS"

